{
  "apiVersion": 1,
  "datasources":
    [
      {
        "name": "Prometheus",
        "type": "prometheus",
        "access": "proxy",
        "url": "http://prometheus:9090",
        "isDefault": true,
        "editable": true,
      },
      {
        "name": "PostgreSQL",
        "type": "postgres",
        "access": "proxy",
        "url": "postgres:5432",
        "database": "dataenginerflow360",
        "user": "postgres",
        "secureJsonData": { "password": "postgres" },
        "jsonData": { "sslmode": "disable", "postgresVersion": 1500 },
        "editable": true,
      },
    ],
}
